# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: timer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0btimer.proto\x12\x05timer\"\x1b\n\x07TimeReq\x12\x10\n\x08TimeZone\x18\x01 \x01(\t\"\x1a\n\x08TimeResp\x12\x0e\n\x06Result\x18\x01 \x01(\t2<\n\x0bTimeService\x12-\n\x08giveTime\x12\x0e.timer.TimeReq\x1a\x0f.timer.TimeResp\"\x00\x62\x06proto3')



_TIMEREQ = DESCRIPTOR.message_types_by_name['TimeReq']
_TIMERESP = DESCRIPTOR.message_types_by_name['TimeResp']
TimeReq = _reflection.GeneratedProtocolMessageType('TimeReq', (_message.Message,), {
  'DESCRIPTOR' : _TIMEREQ,
  '__module__' : 'timer_pb2'
  # @@protoc_insertion_point(class_scope:timer.TimeReq)
  })
_sym_db.RegisterMessage(TimeReq)

TimeResp = _reflection.GeneratedProtocolMessageType('TimeResp', (_message.Message,), {
  'DESCRIPTOR' : _TIMERESP,
  '__module__' : 'timer_pb2'
  # @@protoc_insertion_point(class_scope:timer.TimeResp)
  })
_sym_db.RegisterMessage(TimeResp)

_TIMESERVICE = DESCRIPTOR.services_by_name['TimeService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TIMEREQ._serialized_start=22
  _TIMEREQ._serialized_end=49
  _TIMERESP._serialized_start=51
  _TIMERESP._serialized_end=77
  _TIMESERVICE._serialized_start=79
  _TIMESERVICE._serialized_end=139
# @@protoc_insertion_point(module_scope)
